### ISSUE TITLE
Panic when parsing argument list with an empty string

### ISSUE THREAD

**Issue by rollcat** [timtadh/getopt#2]
The following code:

```go
package main

import (
	"github.com/timtadh/getopt"
	"os"
)

func main() {
	getopt.GetOpt(os.Args[1:], "x", nil)
}
```

Will cause a panic when invoked like this (note an empty string passed as the argument):

```shell
go run main.go ''
```

This is the stack trace:

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/timtadh/getopt.GetOpt({0xc0000ba010, 0x1, 0x1}, {0x496fa3?, 0x0?}, {0x0, 0x0, 0x0})
	.../go/pkg/mod/github.com/timtadh/getopt@v1.0.1/getopt.go:114 +0xaac
main.main()
	.../main.go:9 +0x65
exit status 2
```

The relevant bit in getopt.go:

```go
	for i, arg := range args {
		leftovers = leftovers[1:]
		if arg == "--" {
			if skip {
				err := fmt.Errorf("expected an argument for %q got --", emitopt)
				return nil, nil, err
			}
			break
		} else if skip {
			if arg[0] == '-' {
			// ^^^^^^
				msg := fmt.Sprintf("expected an argument for %q got %v", emitopt, arg)
				return nil, nil, errors.New(msg)
			}
			optargs = append(optargs, new_optarg(emitopt, arg))
			skip = false
			continue
		}
```

**Comment by timtadh** [comment]
Thanks for the bug report. the fix looks pretty trivial I will try to get at it at some point.
